# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app   
    ports:
      - "3006:3006"  
    environment:
      - RACK_ENV=development
      - DATABASE_URL=postgres://postgres:password@database:5432/myapp
    depends_on:
      - database  

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  
